/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * OpenAPI spec version: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Generic access to an organization or a place of it.
 */
export interface Access { 
    /**
     * Date and time of the moment in which the user entered the place.
     */
    entranceTimestamp: Date;
    /**
     * Date and time of the moment in which the user left the place.
     */
    exitTimestamp: Date;
}