/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * OpenAPI spec version: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The address of an organization.
 */
export interface Address { 
    /**
     * the street where the organization is situated
     */
    street: string;
    /**
     * the number in the street where the organization is situated
     */
    number: number;
    /**
     * the postcode of the city where the organization is situated
     */
    postCode?: number;
    /**
     * the city where the organization is situated
     */
    city: string;
    /**
     * the state where the organization is situated
     */
    state?: string;
}