/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * OpenAPI spec version: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User { 
    /**
     * Authentication service's user unique identifier.
     */
    userId: string;
    /**
     * Organization LDAP server's user unique identifier.
     */
    ldapId?: number;
}