/**
 * Stalker API
 * API di Stalker di Imola Informatica sviluppato da qbteam
 *
 * OpenAPI spec version: 1.0.0
 * Contact: qbteamswe@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { OrganizationAnonymousMovement } from '../model/organizationAnonymousMovement';
import { OrganizationAuthenticatedMovement } from '../model/organizationAuthenticatedMovement';
import { PlaceAnonymousMovement } from '../model/placeAnonymousMovement';
import { PlaceAuthenticatedMovement } from '../model/placeAuthenticatedMovement';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TrackingService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Lets the user track its movement with trackingMode set to anonymous in an organization&#x27;s trackingArea and send it to the system.
     * Tracks the user movement inside the trackingArea of an organization with the anonymous trackingMode.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public trackAnonymousMovementInOrganization(body?: OrganizationAnonymousMovement, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public trackAnonymousMovementInOrganization(body?: OrganizationAnonymousMovement, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public trackAnonymousMovementInOrganization(body?: OrganizationAnonymousMovement, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public trackAnonymousMovementInOrganization(body?: OrganizationAnonymousMovement, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/trackMovement/organization/anonymous`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Lets the user track its movement with trackingMode set to anonymous in a place&#x27;s trackingArea and send it to the system.
     * Tracks the user movement inside the trackingArea of a place of an organization with the anonymous trackingMode.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public trackAnonymousMovementInPlace(body?: PlaceAnonymousMovement, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public trackAnonymousMovementInPlace(body?: PlaceAnonymousMovement, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public trackAnonymousMovementInPlace(body?: PlaceAnonymousMovement, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public trackAnonymousMovementInPlace(body?: PlaceAnonymousMovement, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/trackMovement/place/anonymous`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Lets the user track its movement with trackingMode set to authenticated in an organization&#x27;s trackingArea and send it to the system.
     * Tracks the user movement inside the trackingArea of an organization with the authenticated trackingMode.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public trackAuthenticatedMovementInOrganization(body?: OrganizationAuthenticatedMovement, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public trackAuthenticatedMovementInOrganization(body?: OrganizationAuthenticatedMovement, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public trackAuthenticatedMovementInOrganization(body?: OrganizationAuthenticatedMovement, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public trackAuthenticatedMovementInOrganization(body?: OrganizationAuthenticatedMovement, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/trackMovement/organization/authenticated`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Lets the user track its movement with trackingMode set to authenticated in a place&#x27;s trackingArea and send it to the system.
     * Tracks the user movement inside the trackingArea of a place of an organization with the authenticated trackingMode.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public trackAuthenticatedMovementInPlace(body?: PlaceAuthenticatedMovement, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public trackAuthenticatedMovementInPlace(body?: PlaceAuthenticatedMovement, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public trackAuthenticatedMovementInPlace(body?: PlaceAuthenticatedMovement, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public trackAuthenticatedMovementInPlace(body?: PlaceAuthenticatedMovement, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/trackMovement/place/authenticated`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
